language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bash

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit
