#!/usr/bin/env php
<?php

use GitInfo\Console\Command\ScanCommand;
use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application();

// ... register commands
$application->add( $scan = new ScanCommand() );
$application->setDefaultCommand( $scan->getName(),true );
$application->run();
