<?php


use GitInfo\Bash\Local;
use PHPUnit\Framework\TestCase;


class LocalConsoleTest extends TestCase {

	/**
	 * @var Local
	 */
	protected $console;

	public function testExec() {
		$result = $this->console->exec( 'ls -la ' . __DIR__ );
		$this->assertNotEmpty( $result );
		$this->assertTrue( $this->console->isSuccess() );
	}

	protected function setUp() {
		$this->console = new Local();
		parent::setUp(); // TODO: Change the autogenerated stub
	}


}
